# Generated by Django 5.2.6 on 2025-11-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0006_alter_pago_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='lectura_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lectura',
            name='observacion_lectura',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medidor',
            name='consumo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='medidor',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medidor',
            name='ultima_lectura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacionlectura',
            name='mensaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificacionpago',
            name='mensaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
