# Generated by Django 5.2.6 on 2025-11-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0007_cliente_direccion_lectura_lectura_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='ultima_lectura',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
