# Generated by Django 5.2.6 on 2025-11-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0008_alter_medidor_ultima_lectura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidor',
            name='observacion',
        ),
    ]
