# Generated by Django 5.2.6 on 2025-11-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0009_remove_medidor_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='lectura_anterior',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='observacion_lectura',
        ),
    ]
