# Generated by Django 5.2.6 on 2025-11-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0010_remove_lectura_lectura_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='costo_base',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='descripcion',
        ),
    ]
