# Generated by Django 5.2.6 on 2025-11-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0011_remove_tarifa_costo_base_remove_tarifa_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionlectura',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='notificacionpago',
            name='mensaje',
        ),
    ]
