# Generated by Django 5.2.6 on 2025-11-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0012_remove_notificacionlectura_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='consumo_energetico',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
